export const PLASTICO_AMBIENTE = [
    { id: '1', title: 'Separe os materiais Papel e papelão:', text: 'Recicle jornais, revistas, caixas de papelão, cadernos usados (sem espiral), entre outros Plástico: Garrafas PET, embalagens plásticas; Vidro: Garrafas e frascos de vidro, sem resíduos; Metal: Latas de alumínio e aço, e devem estar limpas; Resíduos orgânicos: Frutas, vegetais e outros alimentos podem ser compostados; Resíduos não recicláveis: Materiais como espelhos, porcelanas, tecidos devem ser descartados de forma adequada, conforme a orientação local.' },
    { id: '2', title: 'Limpeza dos materiais', text: 'Antes de colocar os itens na lixeira de reciclagem, é fundamental que estejam limpos. Remova restos de alimentos e líquidos, pois isso pode contaminar os materiais recicláveis e dificultar o processo de reutilização.' },
    { id: '3', title: 'Compreenda a coleta seletiva local', text: 'Verifique como funciona a coleta seletiva na sua cidade. Algumas localidades têm lixeiras separadas para diferentes tipos de materiais, enquanto outras fazem a coleta de forma combinada, separando-os na central de reciclagem.' },
    { id: '4', title: 'Evite misturar materiais recicláveis com não recicláveis', text: 'Se os materiais recicláveis forem misturados com resíduos orgânicos ou não recicláveis, todo o lote pode ser comprometido, dificultando o processo de reciclagem.' },
    { id: '5', title: 'Utilize os pontos de coleta especializados', text: 'Alguns tipos de lixo, como pilhas, baterias e eletrodomésticos, precisam ser descartados em pontos de coleta especializados, pois podem ser tóxicos ou difíceis de reciclar no sistema comum.' },
    { id: '6', title: 'Eduque-se sobre os símbolos de reciclagem', text: 'Familiarize-se com os símbolos de reciclagem presentes nas embalagens, que indicam o tipo de material utilizado e se ele pode ou não ser reciclado. Isso ajuda a fazer escolhas mais conscientes no momento da compra.' },
    { id: '7', title: 'Incentive a reciclagem em sua comunidade', text: 'Compartilhe suas práticas de reciclagem com amigos e familiares, participe de programas locais de conscientização e ajude a educar outros sobre a importância desse hábito para o meio ambiente. Seguindo esses passos, você contribui de forma significativa para a redução do desperdício, a preservação dos recursos naturais e a criação de um futuro mais sustentável.' },
];

export const PLASTIC_MAR_TERRA =[
    {id: '1', title: 'Pláticos no Mar e na Terra', text: 'O plástico, apesar de sua praticidade, é um dos maiores vilões do meio ambiente. Ele leva séculos para se decompor, poluindo nossos oceanos, rios e florestas, prejudicando a vida selvagem e comprometendo o equilíbrio da natureza. No entanto, cada um de nós tem o poder de mudar esse cenário. Ao reduzir o uso de plásticos descartáveis, optar por alternativas sustentáveis e reciclar corretamente, podemos diminuir o impacto desse material e proteger nosso planeta. Pequenas atitudes, quando adotadas por todos, podem transformar o futuro. Vamos fazer nossa parte e agir agora, antes que o plástico se torne um legado de destruição'},
    {id: '2', title: 'Pláticos no Mar e na Terra', text: 'As ilhas de plástico são enormes concentrações de lixo marinho, formadas principalmente por plásticos que acabam nos oceanos e se acumulam devido às correntes marítimas. Essas "ilhas" flutuantes, como a famosa Grande Mancha de Lixo do Pacífico, representam uma grave ameaça ao meio ambiente, pois afetam a vida marinha, que ingere ou fica presa nos plásticos. O impacto é devastador, mas ainda há tempo para agir. Reduzir o uso de plásticos, adotar práticas de reciclagem e apoiar iniciativas de limpeza dos oceanos são passos essenciais para evitar que essas ilhas cresçam ainda mais. Juntos, podemos salvar os oceanos e a vida que depende deles!'},

];
export const R_DESPERDICIO =[
    {id: '1',title: 'Redução de Desperdício', text: 'A redução do desperdício é um ato de consciência e responsabilidade que pode transformar o nosso futuro. Cada item que desperdiçamos representa não apenas um recurso que poderia ser melhor aproveitado, mas também uma oportunidade de fazer a diferença no mundo. Quando optamos por consumir de forma mais cuidadosa e consciente, estamos contribuindo para um planeta mais equilibrado, mais sustentável e mais justo para todos.'},
    {id: '2',title: 'Redução de Desperdício', text: 'Reduzir o desperdício não é apenas uma questão de economizar, mas de repensar nossos hábitos diários. Ao escolher produtos com menos embalagens, ao priorizar o que realmente precisamos e ao evitar o consumo excessivo, estamos ajudando a preservar recursos naturais, economizar energia e reduzir a poluição. Menos desperdício significa menos lixo, menos contaminação e menos pressão sobre os ecossistemas que sustentam a vida no planeta.'},
    {id: '3',title: 'Redução de Desperdício', text: 'A redução do desperdício também se reflete em ações simples, mas poderosas, como reaproveitar alimentos, consertar objetos em vez de descartá-los e doar o que não usamos. Cada uma dessas atitudes é um passo em direção a um mundo mais equilibrado, onde o respeito pelos recursos naturais se torna a base de nossas escolhas. Não é apenas sobre consumir menos, mas consumir melhor, com mais sabedoria e menos excessos.'},
];

export const I_RECICLAGEM =[
    {id: '1',title: 'Importância da Reciclagem', text: 'A reciclagem é mais do que uma simples tarefa; é um ato de responsabilidade que reflete o cuidado com o nosso planeta e as futuras gerações. A cada vez que escolhemos reciclar, estamos contribuindo para a preservação dos recursos naturais, reduzindo o desperdício e diminuindo a poluição que afeta nossos ecossistemas. A natureza, que nos oferece tudo o que precisamos para viver, também precisa da nossa ajuda para se manter equilibrada.'},
    {id: '2',title: 'Importância da Reciclagem', text: 'Quando reciclamos, transformamos materiais que seriam descartados em novos produtos, evitando que eles acabem em aterros sanitários ou no meio ambiente, onde podem levar anos para se decompor. Além disso, a reciclagem também economiza energia e reduz a emissão de gases poluentes, que são responsáveis pelo aquecimento global e outros impactos ambientais.'},
    {id: '3',title: 'Importância da Reciclagem', text: 'Cada pequena ação conta. Não importa se você é um indivíduo ou parte de uma grande comunidade, a mudança começa no seu esforço diário. Ao separar o lixo, escolher produtos recicláveis e incentivar outras pessoas a fazerem o mesmo, você está se tornando um agente de transformação. A consciência de que nossos hábitos de consumo podem afetar o mundo à nossa volta nos fortalece e nos inspira a fazer escolhas mais sustentáveis.'},
    {id: '4',title: 'Importância da Reciclagem', text: 'A reciclagem não é apenas sobre o presente, mas sobre o futuro. Quando escolhemos cuidar do planeta, estamos criando um legado de respeito e harmonia com a Terra, algo que será desfrutado pelas próximas gerações. Cada gesto, por menor que seja, tem o poder de transformar o nosso futuro, porque o que fazemos hoje reflete diretamente no amanhã.'},
    {id: '5',title: 'Importância da Reciclagem', text: 'Portanto, recicle. Inspire aqueles ao seu redor a fazerem o mesmo. Juntos, podemos construir um mundo mais limpo, mais verde e mais sustentável. O planeta agradece e as gerações futuras também.'},
]